### ISSUE TITLE
__fuse is not defined error

### ISSUE THREAD

**Issue by dpinart-uxland** [fuse-box/fuse-mono#1]
Hello,

I'm really new with fusy-box. I discovered fuse-box while searching an alternative to webpack (I hate it) and I think it can fit my needs. I do usually work with monorepos using lerna -only one node_modules for all the pakages- Scafolding is as follows:
my-repo/
&nbsp;&nbsp;&nbsp;&nbsp;packages/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;main-app/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;src/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;index.ts
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sub-app1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;sub-app2

I just installed fuse-box@next  (4.0.0) and tried to serve my app with fuse-box.  Main-app is quite sempla right now and it has no any reference to any sub-app yet. My index.ts just tries to print "hello world". 

I've tried to configure fuse.ts with

```js
import { fusebox } from 'fuse-box';
const fuse = fusebox({
    output: '../../dist/project',
    homeDir: '../../', // we are going all the way up to "monorepo" folder
    entry: 'packages/app/src/index.ts', // entry is relative to "monorepo" folder
    devServer: true,
    webIndex: true
});

fuse.runDev();
```

but when starting app I get 
 FATAL  Entry point doesn't exist

  - C:\Projects\Galenicum\galenicumapp\packages\app\packages\app\src\index.ts
  - Entry point path must be absolute or relative to the fuse file

So I modified fuse.ts as follows

``` js
import { fusebox } from 'fuse-box';
const fuse = fusebox({
    output: '../../dist/project',
    homeDir: '../../', // we are going all the way up to "monorepo" folder
    entry: 'src/index.ts', // entry is relative to "monorepo" folder
    devServer: true,
    webIndex: true
});

fuse.runDev();
```

this time, building runs fine but when browsing to localhost;4444 nothing appears and console shows 2 errors
Uncaught ReferenceError: f is not defined
    at app.js:3
    at app.js:27
vendor.js:1 Uncaught ReferenceError: __fuse is not defined
    at vendor.js:1

Of course I'm doing something wrong, but don't know what.

**Comment by nchanged** [comment]
@dpinart-uxland Hi

I think [this](https://github.com/fuse-box/fuse-box/tree/master/playground/ts-monorepo-1) might help you and [this](https://github.com/fuse-box/fuse-box/tree/master/playground/ts-monorepo-2) This is an outdated repository and should be replaced with the latest approach.

**Comment by dpinart-uxland** [comment]
Thanks so much. It's working nice. I think fuse-box is promising, I now need to dive further and see if it's worth to switch from webpack
